---
- include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Set conf dir fact
  set_fact: postgresql_conf_dir={{ postgresql_conf_dir_default }}
  when: postgresql_conf_dir is not defined

- name: Set data dir fact
  set_fact: postgresql_pgdata={{ postgresql_pgdata_default }}
  when: postgresql_pgdata is not defined

- import_tasks: "setup-ubuntu.yml"
  when: ansible_distribution == 'Ubuntu'

# Install
- name: Install ca-certificates
  yum:
    name:
      - ca-certificates
    state: present
  when: ansible_distribution == 'CentOS'

- name: Install repository Centos
  yum:
    name:
      - "{{ yum_repository_url_centos }}"
    state: present
  when: ansible_distribution == 'CentOS'

- name: Install Postgres Centos
  yum:
    name:
      - "postgresql{{ postgresql_pk_number }}"
      - "postgresql{{ postgresql_pk_number }}-server"
      - "postgresql{{ postgresql_pk_number }}-contrib"
    state: present
  when:
    - ansible_pkg_mgr == 'yum'
    - ansible_distribution == 'CentOS'

- name: Check data directory is not empty
  find:
    paths: "{{ postgresql_pgdata }}"
  register: tmp_pg_data_directory_is_empty
  # when: ansible_distribution == 'CentOS'
 
- name: InitDB
  shell: "{{ postgresql_setup }} initdb"
  environment:
    PGSETUP_INITDB_OPTIONS: "{{ postgresql_initdb_params }}"
  when:
    - postgresql_initdb == true
    # - ansible_distribution == 'CentOS'
    - tmp_pg_data_directory_is_empty.matched|int == 0

# --- Configuration (postgresql.conf)
- name: Configure global settings (postgresql.conf).
  lineinfile:
    dest: "{{ postgresql_conf_dir }}/postgresql.conf"
    regexp: "^#?{{ item.option }}.+$"
    line: "{{ item.option }} = {{ item.value }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ postgresql_conf }}"
  notify: Postgresql restart

- name: Service start and enable (systemd)
  systemd:
    name: "{{ postgresql_service_name }}"
    state: started
    enabled: yes
  when: ansible_distribution == 'CentOS'

# --- Addons
- import_tasks: cube.yml
  when:
    - pg_cube_build == true
#    - ansible_distribution == 'CentOS'

- import_tasks: postgis.yml
  when:
    - pg_postgis_build == true

- import_tasks: citus.yml
  when:
    - pg_citus_build == true

- import_tasks: wal2json.yml
  when:
    - pg_wal2json_build == true

- import_tasks: plr.yml
  when:
    - pg_plr_build == true

- import_tasks: plpython.yml
  when:
    - pg_plpython_build == true